### ISSUE TITLE
Data Split

### ISSUE THREAD

**Issue by pujacomputes** [illidanlab/MoCL-DK#3]
Hi, thanks for sharing this great work! 

I was wondering what split you used when getting results for Table 3? I noticed that "random split" is set as the default in the evaluation script, which is different from the "scaffold" split used in "Pretraining GNNs?" 

I understand that you are not in a transfer learning setting, but I was wondering if you had results for how MoCL did with the scaffold split as well. Curious to see if the addition of domain knowledge has a bigger impact when the split is more difficult.

**Comment by mengyings** [comment]
We used random split for all comparison methods in Table 3 (baselines were also re-run using the same random split). haven't tried scaffold split but definitely interesting to check that too
