### ISSUE TITLE
How to generate rule_indicator_new.pkl and sim_matrix_nb_xx.pkl

### ISSUE THREAD

**Issue by agave233** [illidanlab/MoCL-DK#4]
Hi,
Thanks for your great work! 
I have tried running the model for other datasets (such as esol and freesolv), and I find there should be two preprocessed files : rule_indicator_new.pkl  sim_matrix_nb_xx.pkl. Could you please share the preprocessed code?

Thanks!

**Comment by mengyings** [comment]
Hi the guide for generating rule_indicator matrix and sim_matrix_nb_{neighbor_size} matrix has been updated in the README file (following Key files Section). The corresponding code file pre_structure.py has also been uploaded.
